name: Linting and formatting

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

jobs:
    lint:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.1

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4.0.0
              with:
                node-version: ${{ matrix.node-version }}
      
            - name: Install dependencies
              run: yarn install

            - name: Run Lint
              run: yarn lint && yarn format:check && yarn lint-staged
